import { TestConfig } from '@/types/test';

export const careerPowerTest: TestConfig = {
  slug: 'career-power',
  title: 'AI 직장인 퇴사/이직 전투력 측정기',
  description: '20개 문항으로 분석하는 나의 직장 내 생존 유형과 10가지 커리어 페르소나',
  category: 'career',
  isDataCollection: true,
  questions: [
    {
      id: 1,
      question: '일요일 저녁 9시, 당신의 기분과 행동은?',
      options: [
        { text: '내일 출근할 생각에 가슴이 답답하고 두통/소화불량이 온다', scoreTag: 'T01', dataValue: 'burnout_high' },
        { text: '월요일 오전 회의 안건과 우선순위 업무를 미리 정리한다', scoreTag: 'T02', dataValue: 'proactive' },
        { text: '어차피 내일 일은 내일의 내가 하겠지 하며 넷플릭스를 본다', scoreTag: 'T05', dataValue: 'chill' },
        { text: '이번 주에 지원할 채용 공고와 헤드헌터 연락을 체크한다', scoreTag: 'T03', dataValue: 'hunting' },
      ],
    },
    {
      id: 2,
      question: '상사가 납득하기 어려운 무리한 업무를 지시했을 때?',
      options: [
        { text: '속으로 퇴사 다짐을 백 번 하며 일단 알겠다고 한다', scoreTag: 'T01', dataValue: 'passive_endure' },
        { text: '근거 데이터와 현실적 대안을 정리해 정중히 조율한다', scoreTag: 'T04', dataValue: 'assertive' },
        { text: '팀장님의 정치적 의도를 파악하고 핵심 관계자 라인을 탄다', scoreTag: 'T06', dataValue: 'politic' },
        { text: '이 일도 이직 포트폴리오에 성과 한 줄로 쓸 수 있을지 계산한다', scoreTag: 'T03', dataValue: 'portfolio_add' },
      ],
    },
    {
      id: 3,
      question: '출근 후 모니터를 켜고 가장 먼저 띄우는 창은?',
      options: [
        { text: '원티드, 링크드인, 잡코리아 등 채용 플랫폼', scoreTag: 'T03', dataValue: 'job_portal' },
        { text: '사내 메신저, 일정 캘린더, 오늘자 투두리스트', scoreTag: 'T02', dataValue: 'task_tool' },
        { text: '개인 노션, 사이드 프로젝트 코드, 부업 관리창', scoreTag: 'T07', dataValue: 'side_hustle' },
        { text: '사내 블라인드, 주식/코인 창, 연예 뉴스', scoreTag: 'T05', dataValue: 'distraction' },
      ],
    },
    {
      id: 4,
      question: '팀 내에서 갑작스럽게 대형 사고(장애/결품)가 터졌을 때?',
      options: [
        { text: '내 탓인 것만 같아 심장이 철렁하고 멘탈이 흔들린다', scoreTag: 'T01', dataValue: 'self_blame' },
        { text: '원인 파악 및 롤백/수습 프로세스를 가장 먼저 주도한다', scoreTag: 'T04', dataValue: 'troubleshooter' },
        { text: '내 R&R 영역이 아니길 빌며 침묵을 유지한다', scoreTag: 'T05', dataValue: 'avoidance' },
        { text: '위기를 기회로 삼아 경영진 눈에 띌 수습 보고서를 작성한다', scoreTag: 'T08', dataValue: 'exec_track' },
      ],
    },
    {
      id: 5,
      question: '점심시간 동료들과의 주된 대화 스타일은?',
      options: [
        { text: '회사/상사 뒷담화를 하며 쌓인 화를 푼다', scoreTag: 'T01', dataValue: 'venting' },
        { text: '동종업계 타사 연봉, 이직 썰, 시장 처우 이야기', scoreTag: 'T03', dataValue: 'market_intel' },
        { text: '사내 권력 구도, 이번 인사 평가 소문 탐색', scoreTag: 'T06', dataValue: 'gossip_power' },
        { text: '자연으로 떠나고 싶다며 제주/해외 힐링 여행 이야기', scoreTag: 'T10', dataValue: 'escape_talk' },
      ],
    },
    {
      id: 6,
      question: '연봉 협상 시즌, 당신이 취하는 행동은?',
      options: [
        { text: '회사가 주는 대로 사인하고 조용히 속앓이한다', scoreTag: 'T01', dataValue: 'passive_pay' },
        { text: '1년간의 정량적 기여도 지표와 성과 보고서를 들고 협상한다', scoreTag: 'T02', dataValue: 'data_pay' },
        { text: '이미 타사 오퍼레터를 받아 쥐고 카운터 오퍼를 던진다', scoreTag: 'T03', dataValue: 'counter_offer' },
        { text: '어차피 내 본업 외 수익(부업/투자)이 더 크니 덤덤하다', scoreTag: 'T07', dataValue: 'multi_income' },
      ],
    },
    {
      id: 7,
      question: '퇴근 10분 전, 상사의 돌발 야근 요청이 들어왔다면?',
      options: [
        { text: '약속을 취소하고 눈치 보며 기어이 남아서 일한다', scoreTag: 'T01', dataValue: 'cannot_say_no' },
        { text: '선약 핑계를 대거나 정시 퇴근 알람과 동시에 가방을 싼다', scoreTag: 'T05', dataValue: 'strict_leave' },
        { text: '남아서 하되, 초과근무 수당과 인사고과 반영을 당당히 요구한다', scoreTag: 'T08', dataValue: 'reward_driven' },
        { text: '내 독립 기술로 외주/창업하면 이 시간에 내 돈을 벌 텐데 한탄한다', scoreTag: 'T09', dataValue: 'entrepreneur_mind' },
      ],
    },
    {
      id: 8,
      question: '나에게 지금 이 직장과 회사의 의미는?',
      options: [
        { text: '나를 갈아 넣는 곳이지만 생계를 위해 어쩔 수 없는 감옥', scoreTag: 'T01', dataValue: 'jail' },
        { text: '전문성을 쌓고 내 이름 석 자를 브랜딩하는 훈련소', scoreTag: 'T04', dataValue: 'training_camp' },
        { text: '최소한의 에너지로 월급을 교환하는 정기 구독지', scoreTag: 'T05', dataValue: 'subscription' },
        { text: '언젠가 내 사업을 차리기 위한 비즈니스 모델 학습장', scoreTag: 'T09', dataValue: 'business_lab' },
      ],
    },
    {
      id: 9,
      question: '주말이나 연휴에 울리는 사내 메신저 알림을 봤을 때?',
      options: [
        { text: '심장이 쿵쾅거리고 휴일 내내 불안감이 지속된다', scoreTag: 'T01', dataValue: 'weekend_anxiety' },
        { text: '궁금증을 못 참아 확인하고 바로 피드백을 남긴다', scoreTag: 'T02', dataValue: 'always_connected' },
        { text: '월요일 오전 9시 전까지 앱 자체를 쳐다보지 않는다', scoreTag: 'T05', dataValue: 'app_ignore' },
        { text: '사내 정치적 중요도에 따라 상사 메시지만 골라 답장한다', scoreTag: 'T06', dataValue: 'selective_reply' },
      ],
    },
    {
      id: 10,
      question: '회사에서 동료들과의 관계 설정은?',
      options: [
        { text: '비즈니스 관계일 뿐, 퇴근하면 남남이다', scoreTag: 'T05', dataValue: 'strict_boundary' },
        { text: '언젠가 창업할 때 함께할 믿음직한 팀원을 물색한다', scoreTag: 'T09', dataValue: 'co_founder_hunt' },
        { text: '실세 라인과 긴밀한 유대 관계를 형성해 우군을 만든다', scoreTag: 'T06', dataValue: 'power_network' },
        { text: '사내 인간관계 스트레스 자체가 너무 지치고 버겁다', scoreTag: 'T10', dataValue: 'people_exhaust' },
      ],
    },
    {
      id: 11,
      question: '업무 중 새로운 AI 툴이나 신기술이 도입되었을 때?',
      options: [
        { text: '기능을 파고들어 남들보다 3배 빠르게 자동화 파이프라인을 짠다', scoreTag: 'T04', dataValue: 'tech_expert' },
        { text: '업무 속도를 줄여서 확보된 여유 시간에 사이드잡을 돌린다', scoreTag: 'T07', dataValue: 'automate_side' },
        { text: '신기술 도입 성과를 전사 보고서로 만들어 임원진에 어필한다', scoreTag: 'T08', dataValue: 'exec_showcase' },
        { text: '배우는 것 자체가 또 다른 업무 부담으로 느껴져 피곤하다', scoreTag: 'T10', dataValue: 'fatigue' },
      ],
    },
    {
      id: 12,
      question: '팀 회식 자리에 참석했을 때 당신의 행동은?',
      options: [
        { text: '기 빨려서 화장실에 자주 가거나 1차 끝나고 바로 탈출한다', scoreTag: 'T10', dataValue: 'introvert_escape' },
        { text: '의사결정권자 옆자리를 사수하며 프로젝트 지원을 약속받는다', scoreTag: 'T06', dataValue: 'seating_strategy' },
        { text: '고기 굽기나 건배사 따위 신경 안 쓰고 조용히 먹기만 한다', scoreTag: 'T05', dataValue: 'food_focus' },
        { text: '업계 최신 동향과 타사 정보 이야기로 주도권을 잡는다', scoreTag: 'T03', dataValue: 'market_lead' },
      ],
    },
    {
      id: 13,
      question: '사내에서 불합리하거나 비효율적인 프로세스를 발견했다면?',
      options: [
        { text: '어차피 내 회사도 아닌데 굳이 긁어부스럼 만들지 않는다', scoreTag: 'T05', dataValue: 'let_it_be' },
        { text: '혼자 힘으로 도구를 만들어 내 파트 업무만 깔끔히 자동화한다', scoreTag: 'T04', dataValue: 'solo_automate' },
        { text: '혁신 제안서로 패키징하여 조직 개편 기회로 삼는다', scoreTag: 'T08', dataValue: 'org_reform' },
        { text: '이런 비효율을 해결하는 B2B SaaS 사업 아이템으로 기록해 둔다', scoreTag: 'T09', dataValue: 'saas_idea' },
      ],
    },
    {
      id: 14,
      question: '이직 제안(헤드헌터 커피챗)이 들어왔을 때?',
      options: [
        { text: '처우와 스톡옵션 조건을 꼼꼼히 비교하며 몸값을 올린다', scoreTag: 'T03', dataValue: 'value_up' },
        { text: '현재 직장에서 맡은 핵심 프로젝트가 끝날 때까지 사양한다', scoreTag: 'T02', dataValue: 'loyal_work' },
        { text: '회사 옮겨봤자 다 똑같은 지옥일 것 같아 무기력하다', scoreTag: 'T01', dataValue: 'hopeless' },
        { text: '완전 재택근무나 워케이션 지원 여부부터 확인한다', scoreTag: 'T10', dataValue: 'remote_first' },
      ],
    },
    {
      id: 15,
      question: '회사에서 가장 큰 보람이나 희열을 느끼는 순간은?',
      options: [
        { text: '아무도 못 풀던 복잡한 기술/난제를 깔끔하게 해결했을 때', scoreTag: 'T04', dataValue: 'craftsmanship' },
        { text: '내 제안이 채택되어 전사 임원 회의에서 스포트라이트를 받을 때', scoreTag: 'T08', dataValue: 'spotlight' },
        { text: '칼퇴하고 지하철 타는 순간과 통장에 월급 찍히는 알림', scoreTag: 'T05', dataValue: 'payday_leave' },
        { text: '내 사이드 비즈니스 알림창에 첫 자동 결제가 찍혔을 때', scoreTag: 'T07', dataValue: 'stripe_alert' },
      ],
    },
    {
      id: 16,
      question: '사내 인사 평가에서 불공정한 결과를 통보받았다면?',
      options: [
        { text: '억울함에 밤새 잠을 못 자고 자존감이 무너진다', scoreTag: 'T01', dataValue: 'self_harm' },
        { text: '이 회사는 끝났다 판단하고 그날 밤 당장 이력서를 업데이트한다', scoreTag: 'T03', dataValue: 'instant_apply' },
        { text: '평가권자와 1:1 면담을 잡아 소명 자료를 요구하고 바로잡는다', scoreTag: 'T02', dataValue: 'protest' },
        { text: '회사에 주는 에너지를 30%로 줄이고 부업에 집중한다', scoreTag: 'T07', dataValue: 'quiet_shift' },
      ],
    },
    {
      id: 17,
      question: '내가 생각하는 진정한 커리어의 성공이란?',
      options: [
        { text: '빠르게 승진하여 C레벨 임원이나 조직의 수장이 되는 것', scoreTag: 'T08', dataValue: 'c_level' },
        { text: '내 고유한 기술로 시장에서 대체 불가능한 권위를 갖는 것', scoreTag: 'T04', dataValue: 'expert_authority' },
        { text: '장소와 시간에 구애받지 않고 스스로 돈을 버는 경제적 자유', scoreTag: 'T09', dataValue: 'freedom' },
        { text: '적당한 소득과 건강, 무탈한 일상이 이어지는 워라밸', scoreTag: 'T10', dataValue: 'peaceful_life' },
      ],
    },
    {
      id: 18,
      question: '업무 시간 중 딴짓을 하거나 여유가 생기면?',
      options: [
        { text: '틈틈이 개인 부업, 블로그 포스팅, 코딩, 공부를 한다', scoreTag: 'T07', dataValue: 'personal_growth' },
        { text: '비행기 표 검색, 캠핑 용품, 시골살이 브이로그를 본다', scoreTag: 'T10', dataValue: 'nature_search' },
        { text: '다음 분기 프로젝트 기획서를 미리 써둔다', scoreTag: 'T02', dataValue: 'advance_work' },
        { text: '그냥 멍때리며 커피 마시고 온다', scoreTag: 'T05', dataValue: 'idle' },
      ],
    },
    {
      id: 19,
      question: '나를 가장 힘들게 만드는 직장 내 스트레스 요인은?',
      options: [
        { text: '능력도 없으면서 라인만 타는 상사와 사내 정치판', scoreTag: 'T04', dataValue: 'hates_politics' },
        { text: '열심히 해도 인정해주지 않는 보상 체계와 가스라이팅', scoreTag: 'T01', dataValue: 'gaslighted' },
        { text: '내 잠재력을 다 쏟아붓지 못하게 가로막는 관료주의', scoreTag: 'T09', dataValue: 'bureaucracy' },
        { text: '숨 막히는 출퇴근길과 하루 종일 이어지는 사람 간의 부대낌', scoreTag: 'T10', dataValue: 'commute_crowd' },
      ],
    },
    {
      id: 20,
      question: '지금 당장 3개월의 유급휴가가 주어진다면?',
      options: [
        { text: '스마트폰 끄고 제주도나 동남아 휴양지로 날아가 푹 쉰다', scoreTag: 'T10', dataValue: 'recharge_escape' },
        { text: 'MVP 서비스를 완성하여 프로덕트 헌트에 론칭해 본다', scoreTag: 'T09', dataValue: 'launch_mvp' },
        { text: '이직 포트폴리오를 완벽히 정비하고 탑티어 기업에 면접을 본다', scoreTag: 'T03', dataValue: 'interview_prep' },
        { text: '글로벌 자격증 취득 및 전문가 네트워킹을 확장한다', scoreTag: 'T08', dataValue: 'executive_prep' },
      ],
    },
  ],
  results: {
    T01: {
      code: 'T01',
      title: '방전된 야근 요정 (위험 경보)',
      subtitle: '배터리 잔량 3%, 긴급 리프레시 및 이직 준비 시급',
      description: '책임감은 강하지만 무너진 워라밸과 가스라이팅 환경으로 에너지가 고갈된 상태입니다. 나를 갉아먹는 환경에서 혼자 버티는 것은 미덕이 아닙니다. 지금 당장 감정을 배제하고 이력서를 정리해 탈출 계획을 세우세요.',
      tags: ['#심각한번아웃', '#탈출마려움', '#멘탈케어시급', '#퇴사각'],
      bestMatch: '월급 가성비 극대화 프로퇴근러 (T05)',
      worstMatch: '성과 주도형 불도저 (T02)',
    },
    T02: {
      code: 'T02',
      title: '성과 주도형 불도저 (정통 엘리트)',
      subtitle: '정량적 지표와 실행력으로 증명하는 조직의 기둥',
      description: '높은 주도성과 완벽주의를 갖춘 인재입니다. 맡은 프로젝트를 반드시 성공시키는 추진력이 있습니다. 다만 회사가 나의 헌신을 당연시하지 않도록 연봉 협상과 보상 테이블을 명확히 주도해야 합니다.',
      tags: ['#성과제조기', '#실행력만렙', '#프로일잘러', '#핵심인재'],
      bestMatch: '임원 트랙 고속승진마 (T08)',
      worstMatch: '방전된 야근 요정 (T01)',
    },
    T03: {
      code: 'T03',
      title: '연봉 점프 헌터 (전투형 이직러)',
      subtitle: '회사를 철저히 디딤돌로 활용하는 시장가치 최상위자',
      description: '시장 감각과 전투력이 최고 수준입니다. 회사의 네임밸류와 현재 업무를 자신의 이력서 성과로 전환하는 능력이 탁월합니다. 조만간 파격적인 조건으로 이직할 확률이 가장 높습니다.',
      tags: ['#이직준비완료', '#시장가치최상', '#협상달인', '#헤드헌터단골'],
      bestMatch: '대체불가 고독한 기술 장인 (T04)',
      worstMatch: '방전된 야근 요정 (T01)',
    },
    T04: {
      code: 'T04',
      title: '대체불가 고독한 기술 장인 (스페셜리스트)',
      subtitle: '사내 정치 대신 실력과 전문성으로 승부하는 전문가',
      description: '정치질과 탁상공론을 극도로 혐오하며, 문제 해결과 실력으로 인정받는 기술자입니다. 당신의 전문성은 회사가 함부로 건드릴 수 없는 무기입니다. 독립적인 포지션을 유지하며 몸값을 높이세요.',
      tags: ['#스페셜리스트', '#기술장인', '#정치극혐', '#실력파'],
      bestMatch: '연봉 점프 헌터 (T03)',
      worstMatch: '사내 정치의 흑막 제갈공명 (T06)',
    },
    T05: {
      code: 'T05',
      title: '월급 가성비 극대화 프로퇴근러 (생존왕)',
      subtitle: '최소의 에너지 투입으로 최대의 멘탈을 지키는 갓생러',
      description: '칼퇴와 워라밸의 절대 수호자입니다. 적당한 거리두기로 회사 스트레스를 제로에 수렴하게 관리합니다. 다만 시장에서의 개인 경쟁력이 도태되지 않도록 최소한의 개인 무기는 챙겨두어야 합니다.',
      tags: ['#워라밸수호자', '#칼퇴요정', '#조용한퇴직', '#가성비근무'],
      bestMatch: '방전된 야근 요정 (T01)',
      worstMatch: '성과 주도형 불도저 (T02)',
    },
    T06: {
      code: 'T06',
      title: '사내 정치의 흑막 제갈공명 (전략가)',
      subtitle: '조직의 권력 구도와 실세 라인을 꿰뚫고 있는 판세 마스터',
      description: '조직의 생리와 인간관계를 읽어내는 눈이 탁월합니다. 누구에게 힘을 실어주고 어떤 타이밍에 나서야 하는지 본능적으로 압니다. 조직 내에서 가장 빠르게 안정권을 확보하는 유형입니다.',
      tags: ['#판세마스터', '#사내정치만렙', '#라인타기', '#생존력갑'],
      bestMatch: '임원 트랙 고속승진마 (T08)',
      worstMatch: '대체불가 고독한 기술 장인 (T04)',
    },
    T07: {
      code: 'T07',
      title: '사이드잡 파이프라인 N잡러 (멀티플레이어)',
      subtitle: '본업은 거들 뿐, 다중 수입 파이프라인을 구축한 실속파',
      description: '회사의 월급 하나에 의존하지 않는 스마트한 전략가입니다. 회사 업무를 효율화하고 남는 시간에 부업, 콘텐츠, 투자를 돌립니다. 회사에서 잔소리를 들어도 타격감이 전혀 없습니다.',
      tags: ['#N잡러', '#수익다각화', '#부업마스터', '#타격감제로'],
      bestMatch: '회사 밖이 체질인 예비 창업가 (T09)',
      worstMatch: '성과 주도형 불도저 (T02)',
    },
    T08: {
      code: 'T08',
      title: '임원 트랙 고속승진마 (차기 리더)',
      subtitle: '전사적 관점에서 비즈니스를 바라보는 야망 있는 야전사령관',
      description: '실무자 레벨을 넘어 비즈니스와 경영진의 언어로 소통할 줄 아는 인재입니다. 큰 그림을 그리고 팀을 장악하는 능력이 있어 차기 C레벨이나 임원 트랙 1순위 후보입니다.',
      tags: ['#임원트랙', '#차기리더', '#비즈니스시야', '#야망가'],
      bestMatch: '성과 주도형 불도저 (T02)',
      worstMatch: '자연인 힐링 갈망러 (T10)',
    },
    T09: {
      code: 'T09',
      title: '회사 밖이 체질인 예비 창업가 (빌더)',
      subtitle: '남의 일 대신 내 사업을 만들 준비가 끝난 혁신가',
      description: '조직의 비효율과 관료주의에 답답함을 느끼며, 시장에 직접 서비스를 내놓고 승부하고 싶어 합니다. 지금 겪는 회사의 모든 경험은 미래 당신 비즈니스의 밑거름이 될 것입니다.',
      tags: ['#예비창업가', '#빌더마인드', '#탈회사', '#사업체질'],
      bestMatch: '사이드잡 파이프라인 N잡러 (T07)',
      worstMatch: '월급 가성비 극대화 프로퇴근러 (T05)',
    },
    T10: {
      code: 'T10',
      title: '자연인 힐링 갈망러 (자유 영혼)',
      subtitle: '도심 빌딩숲을 벗어나 한달살기와 쉼이 절실한 영혼',
      description: '치열한 경쟁과 소음 속에서 영혼이 지쳐 있습니다. 지금 당신에게 필요한 것은 추가적인 스펙업이 아니라 온전한 휴식과 자연 속에서의 충전입니다. 워케이션이나 장기 리프레시를 강력히 권장합니다.',
      tags: ['#자연인갈망', '#힐링시급', '#한달살기', '#디지털디톡스'],
      bestMatch: '월급 가성비 극대화 프로퇴근러 (T05)',
      worstMatch: '임원 트랙 고속승진마 (T08)',
    },
  },
  seoArticle: '직장인 번아웃 증후군의 징후와 10가지 커리어 페르소나별 최적의 이직 및 성장 전략을 제시하는 심층 진단 가이드입니다. 자신의 직장 내 생존 전략과 시장 가치를 정확히 파악하여 커리어 로드맵을 설계해 보세요.',
};
