import { TestConfig } from '@/types/test';

export const careerPowerEnTest: TestConfig = {
  slug: 'career-power',
  title: 'AI Workplace Survival & Career Archetype Test',
  description: 'Discover your corporate survival archetype and market value across 20 localized scenarios.',
  category: 'career',
  isDataCollection: true,
  questions: [
    {
      id: 1,
      question: 'Sunday night, 9 PM. What is running through your head?',
      options: [
        { text: 'Severe "Sunday Scaries" with physical tension and anxiety', scoreTag: 'T01', dataValue: 'burnout_high' },
        { text: 'Reviewing calendar and prepping talking points for Monday 9 AM sync', scoreTag: 'T02', dataValue: 'proactive' },
        { text: 'Binge-watching Netflix—tomorrow is Monday-me’s problem', scoreTag: 'T05', dataValue: 'chill' },
        { text: 'Checking incoming recruiter InMails and polishing my LinkedIn profile', scoreTag: 'T03', dataValue: 'hunting' },
      ],
    },
    {
      id: 2,
      question: 'Your manager drops an unrealistic, last-minute project on your plate. You:',
      options: [
        { text: 'Nod and say yes while secretly updating my resume in tears', scoreTag: 'T01', dataValue: 'passive_endure' },
        { text: 'Push back with capacity data and propose a viable phased plan', scoreTag: 'T04', dataValue: 'assertive' },
        { text: 'Analyze who the project sponsor is and leverage it for political visibility', scoreTag: 'T06', dataValue: 'politic' },
        { text: 'Calculate if this project will yield a strong bullet point on my CV', scoreTag: 'T03', dataValue: 'portfolio_add' },
      ],
    },
    {
      id: 3,
      question: 'First browser tab you open when you boot up in the morning:',
      options: [
        { text: 'LinkedIn Jobs, Levels.fyi, or Indeed', scoreTag: 'T03', dataValue: 'job_portal' },
        { text: 'Slack, Google Calendar, and my prioritized Notion task board', scoreTag: 'T02', dataValue: 'task_tool' },
        { text: 'My side-project dashboard, Stripe alerts, or personal codebase', scoreTag: 'T07', dataValue: 'side_hustle' },
        { text: 'Blind, Reddit, or stock/crypto portfolios', scoreTag: 'T05', dataValue: 'distraction' },
      ],
    },
    {
      id: 4,
      question: 'A critical outage or major bug hits production unexpectedly. Your reaction:',
      options: [
        { text: 'Immediate dread and imposter syndrome kicking in hard', scoreTag: 'T01', dataValue: 'self_blame' },
        { text: 'Lead the post-mortem triage, organize rollbacks, and coordinate fixes', scoreTag: 'T04', dataValue: 'troubleshooter' },
        { text: 'Stay silent in the Slack war room hoping it is outside my scope', scoreTag: 'T05', dataValue: 'avoidance' },
        { text: 'Position myself as the hero who saved the day in front of VPs', scoreTag: 'T08', dataValue: 'exec_track' },
      ],
    },
    {
      id: 5,
      question: 'Typical lunch / virtual coffee break conversation topic:',
      options: [
        { text: 'Venting about toxic leadership and organizational chaos', scoreTag: 'T01', dataValue: 'venting' },
        { text: 'Tech stacks, TC (total compensation) benchmarks, and market moves', scoreTag: 'T03', dataValue: 'market_intel' },
        { text: 'Re-org rumors, executive reshuffling, and internal politics', scoreTag: 'T06', dataValue: 'gossip_power' },
        { text: 'Digital nomad destinations and escaping the rat race', scoreTag: 'T10', dataValue: 'escape_talk' },
      ],
    },
    {
      id: 6,
      question: 'Annual compensation review season. What is your playbook?',
      options: [
        { text: 'Accept whatever standard 3% merit increase is offered and sigh', scoreTag: 'T01', dataValue: 'passive_pay' },
        { text: 'Bring a data-backed impact dossier highlighting OKR overachievement', scoreTag: 'T02', dataValue: 'data_pay' },
        { text: 'Already holding a competing signed offer letter for leverage', scoreTag: 'T03', dataValue: 'counter_offer' },
        { text: 'Unfazed—my side hustle and dividend cashflow dwarf my base pay', scoreTag: 'T07', dataValue: 'multi_income' },
      ],
    },
    {
      id: 7,
      question: '15 minutes before logging off, an urgent late request lands. You:',
      options: [
        { text: 'Cancel evening plans with deep resentment and grind through it', scoreTag: 'T01', dataValue: 'cannot_say_no' },
        { text: 'Set Slack status to Offline and close the laptop without guilt', scoreTag: 'T05', dataValue: 'strict_leave' },
        { text: 'Deliver it swiftly, ensuring executive stakeholders notice the extra mile', scoreTag: 'T08', dataValue: 'reward_driven' },
        { text: 'Frustrated that this time could be spent scaling my own SaaS product', scoreTag: 'T09', dataValue: 'entrepreneur_mind' },
      ],
    },
    {
      id: 8,
      question: 'What does your current job fundamentally mean to you?',
      options: [
        { text: 'A soul-draining hamster wheel I endure purely to pay the bills', scoreTag: 'T01', dataValue: 'jail' },
        { text: 'A training ground to hone elite domain expertise and build reputation', scoreTag: 'T04', dataValue: 'training_camp' },
        { text: 'A low-energy transaction exchanging minimal effort for steady cash', scoreTag: 'T05', dataValue: 'subscription' },
        { text: 'A paid business incubator to study organizational mechanics before founding', scoreTag: 'T09', dataValue: 'business_lab' },
      ],
    },
    {
      id: 9,
      question: 'Slack / Teams notification pings on a Saturday afternoon:',
      options: [
        { text: 'Heart rate spikes and weekend tranquility instantly ruined', scoreTag: 'T01', dataValue: 'weekend_anxiety' },
        { text: 'Cannot resist checking and reply within two minutes', scoreTag: 'T02', dataValue: 'always_connected' },
        { text: 'Do not disturb enabled. Won’t open until Monday 9:00 AM', scoreTag: 'T05', dataValue: 'app_ignore' },
        { text: 'Strategically answer only if it comes from key leadership sponsors', scoreTag: 'T06', dataValue: 'selective_reply' },
      ],
    },
    {
      id: 10,
      question: 'How do you view workplace relationships and networking?',
      options: [
        { text: 'Purely transactional—once 5 PM hits, colleagues are strangers', scoreTag: 'T05', dataValue: 'strict_boundary' },
        { text: 'Scouting talent for high-trust potential future co-founders', scoreTag: 'T09', dataValue: 'co_founder_hunt' },
        { text: 'Cultivating strategic alliances with decision-makers who hold influence', scoreTag: 'T06', dataValue: 'power_network' },
        { text: 'Exhausted by forced social interactions and corporate small talk', scoreTag: 'T10', dataValue: 'people_exhaust' },
      ],
    },
    {
      id: 11,
      question: 'When a powerful new AI workflow tool is introduced company-wide:',
      options: [
        { text: 'Master it overnight to build an automated 10x workflow', scoreTag: 'T04', dataValue: 'tech_expert' },
        { text: 'Use time saved from automation to work on personal side businesses', scoreTag: 'T07', dataValue: 'automate_side' },
        { text: 'Spearhead AI adoption initiatives to present to C-level execs', scoreTag: 'T08', dataValue: 'exec_showcase' },
        { text: 'Overwhelmed that another tool is being added to the endless stack', scoreTag: 'T10', dataValue: 'fatigue' },
      ],
    },
    {
      id: 12,
      question: 'Company happy hour or quarterly team dinner:',
      options: [
        { text: 'Social battery drains fast; make an Irish exit after round one', scoreTag: 'T10', dataValue: 'introvert_escape' },
        { text: 'Secure the seat next to leadership to discuss strategic roadmaps', scoreTag: 'T06', dataValue: 'seating_strategy' },
        { text: 'Focus purely on free high-end appetizers and leave quietly', scoreTag: 'T05', dataValue: 'food_focus' },
        { text: 'Network aggressively to gather cross-functional market intel', scoreTag: 'T03', dataValue: 'market_lead' },
      ],
    },
    {
      id: 13,
      question: 'You spot a grossly inefficient operational bottleneck in the company:',
      options: [
        { text: 'Not my circus, not my monkeys. Keep my head down', scoreTag: 'T05', dataValue: 'let_it_be' },
        { text: 'Quietly write a custom script/tool to automate it for my own team', scoreTag: 'T04', dataValue: 'solo_automate' },
        { text: 'Package it as a transformation initiative to expand headcount/budget', scoreTag: 'T08', dataValue: 'org_reform' },
        { text: 'Recognize a validated B2B SaaS pain point and draft a pitch deck', scoreTag: 'T09', dataValue: 'saas_idea' },
      ],
    },
    {
      id: 14,
      question: 'A top-tier recruiter reaches out with an enticing coffee chat invite:',
      options: [
        { text: 'Assess total compensation package, equity upside, and title jump', scoreTag: 'T03', dataValue: 'value_up' },
        { text: 'Politely decline until current key milestones are delivered', scoreTag: 'T02', dataValue: 'loyal_work' },
        { text: 'Feel too mentally drained to even consider going through 5 interview rounds', scoreTag: 'T01', dataValue: 'hopeless' },
        { text: 'Check if they offer 100% remote flexibility and asynchronous culture', scoreTag: 'T10', dataValue: 'remote_first' },
      ],
    },
    {
      id: 15,
      question: 'The moment that gives you the highest dopamine hit at work:',
      options: [
        { text: 'Cracking a complex engineering or architectural challenge solo', scoreTag: 'T04', dataValue: 'craftsmanship' },
        { text: 'Receiving executive shoutouts in all-hands meeting for a winning strategy', scoreTag: 'T08', dataValue: 'spotlight' },
        { text: 'Direct deposit notification hitting my bank account on the 1st and 15th', scoreTag: 'T05', dataValue: 'payday_leave' },
        { text: 'Stripe notification dinging for an automated subscription sale', scoreTag: 'T07', dataValue: 'stripe_alert' },
      ],
    },
    {
      id: 16,
      question: 'You receive an unjust performance review due to corporate politics:',
      options: [
        { text: 'Spiral into severe self-doubt and sleep deprivation', scoreTag: 'T01', dataValue: 'self_harm' },
        { text: 'Immediately trigger aggressive job applications that very evening', scoreTag: 'T03', dataValue: 'instant_apply' },
        { text: 'Request a formal 1-on-1 with calibrated metrics to dispute the score', scoreTag: 'T02', dataValue: 'protest' },
        { text: 'Mentally disengage to 20% effort and pour 80% into freelance revenue', scoreTag: 'T07', dataValue: 'quiet_shift' },
      ],
    },
    {
      id: 17,
      question: 'What defines ultimate career success in your book?',
      options: [
        { text: 'Climbing to the C-suite and steering multi-million dollar orgs', scoreTag: 'T08', dataValue: 'c_level' },
        { text: 'Becoming an irreplaceable domain authority with technical leverage', scoreTag: 'T04', dataValue: 'expert_authority' },
        { text: 'True financial sovereignty—time & location freedom', scoreTag: 'T09', dataValue: 'freedom' },
        { text: 'Zero toxic stress, high work-life balance, and peaceful living', scoreTag: 'T10', dataValue: 'peaceful_life' },
      ],
    },
    {
      id: 18,
      question: 'During unexpected downtime between meetings, you usually:',
      options: [
        { text: 'Ship updates to side gigs, write content, or learn new technical skills', scoreTag: 'T07', dataValue: 'personal_growth' },
        { text: 'Browse remote cabin rentals, flight deals, or nature vlogs', scoreTag: 'T10', dataValue: 'nature_search' },
        { text: 'Draft next quarter’s roadmap proposals ahead of time', scoreTag: 'T02', dataValue: 'advance_work' },
        { text: 'Stare into space sipping specialty coffee with zero guilt', scoreTag: 'T05', dataValue: 'idle' },
      ],
    },
    {
      id: 19,
      question: 'Your single biggest source of workplace friction:',
      options: [
        { text: 'Clueless middle management playing petty political games', scoreTag: 'T04', dataValue: 'hates_politics' },
        { text: 'Gaslighting culture with unrewarded heavy lifting', scoreTag: 'T01', dataValue: 'gaslighted' },
        { text: 'Red tape and bureaucracy suffocating high-impact execution', scoreTag: 'T09', dataValue: 'bureaucracy' },
        { text: 'The mandatory RTO (return to office) push and commute grind', scoreTag: 'T10', dataValue: 'commute_crowd' },
      ],
    },
    {
      id: 20,
      question: 'You are granted a fully paid 3-month sabbatical tomorrow. You:',
      options: [
        { text: 'Turn off notifications and unplug in Bali or the Swiss Alps', scoreTag: 'T10', dataValue: 'recharge_escape' },
        { text: 'Build, launch, and monetize an MVP on Product Hunt', scoreTag: 'T09', dataValue: 'launch_mvp' },
        { text: 'Ace executive interviews for a 40%+ total compensation leap', scoreTag: 'T03', dataValue: 'interview_prep' },
        { text: 'Acquire high-tier executive certifications and expand board networks', scoreTag: 'T08', dataValue: 'executive_prep' },
      ],
    },
  ],
  results: {
    T01: {
      code: 'T01',
      title: 'The Redlining Slogger (Critical Burnout Alert)',
      subtitle: 'Battery at 3% — Urgent environment pivot required',
      description: 'You possess high conscientiousness trapped in an unsupportive ecosystem. Enduring gaslighting is not a badge of honor. Detach emotionally, safeguard your mental bandwidth, and execute an exit strategy immediately.',
      tags: ['#SevereBurnout', '#ExitPlanNeeded', '#MentalDetox', '#Overworked'],
      bestMatch: 'The Master of Quiet Quitting (T05)',
      worstMatch: 'The Relentless Execution Engine (T02)',
    },
    T02: {
      code: 'T02',
      title: 'The Relentless Execution Engine (High Performer)',
      subtitle: 'Anchor of the organization driven by data and delivery',
      description: 'A benchmark operator with exceptional ownership. You consistently deliver above expectations. Ensure leadership does not commoditize your high output—anchor your compensation reviews strictly to quantifiable revenue and efficiency gains.',
      tags: ['#HighPerformer', '#ExecutionKing', '#ReliableAnchor', '#Meritocracy'],
      bestMatch: 'The Fast-Track Executive Nominee (T08)',
      worstMatch: 'The Redlining Slogger (T01)',
    },
    T03: {
      code: 'T03',
      title: 'The Compensation Arbitrage Hunter (Market Shark)',
      subtitle: 'Top-percentile market agility converting tenure into equity leaps',
      description: 'Your market awareness and negotiation prowess are elite. You view corporations as stepping stones to maximize career trajectory and compensation packages. You are primed for rapid career compounding.',
      tags: ['#MarketShark', '#OfferHunter', '#HighTC', '#NegotiationMaster'],
      bestMatch: 'The Autonomous Craft Specialist (T04)',
      worstMatch: 'The Redlining Slogger (T01)',
    },
    T04: {
      code: 'T04',
      title: 'The Autonomous Craft Specialist (Domain Authority)',
      subtitle: 'Deep technical leverage over corporate theatre',
      description: 'You abhor bureaucracy and win purely on craft and undeniable problem-solving. Your domain mastery grants you rare leverage that organizations cannot easily replace. Protect your autonomy fiercely.',
      tags: ['#Specialist', '#CraftOverPolitics', '#HighLeverage', '#DomainMaster'],
      bestMatch: 'The Compensation Arbitrage Hunter (T03)',
      worstMatch: 'The Shadow Corporate Strategist (T06)',
    },
    T05: {
      code: 'T05',
      title: 'The Master of Quiet Quitting (Optimal ROI Operative)',
      subtitle: 'Zero emotional friction, maximum work-life equilibrium',
      description: 'The undisputed master of workplace efficiency. You deliver required baseline expectations while maintaining a pristine boundary between life and work. Just keep your core market skills sharp on the side.',
      tags: ['#QuietQuitting', '#WorkLifeZen', '#OptimalROI', '#ZeroStress'],
      bestMatch: 'The Redlining Slogger (T01)',
      worstMatch: 'The Relentless Execution Engine (T02)',
    },
    T06: {
      code: 'T06',
      title: 'The Shadow Corporate Strategist (Machiavellian Pilot)',
      subtitle: 'Mastering informal power dynamics and organizational coalitions',
      description: 'You navigate corporate hierarchies with finesse. You understand who holds decision-making power and how narratives are constructed. You secure prime projects and insulation with minimal friction.',
      tags: ['#CorporateSavvy', '#PowerDynamics', '#StrategicAlliances', '#SurvivalKing'],
      bestMatch: 'The Fast-Track Executive Nominee (T08)',
      worstMatch: 'The Autonomous Craft Specialist (T04)',
    },
    T07: {
      code: 'T07',
      title: 'The Sovereign Portfolio Builder (Multi-Income Pro)',
      subtitle: 'Single paycheck hedge with multiple cashflow pipelines',
      description: 'You understand that job security is an illusion. You optimize primary work hours to scale independent digital assets, consulting gigs, and automated revenue streams. Workplace micro-politics cannot touch you.',
      tags: ['#SideHustleMaster', '#SovereignCashflow', '#DiversifiedIncome', '#Unbothered'],
      bestMatch: 'The Inevitable SaaS Founder (T09)',
      worstMatch: 'The Relentless Execution Engine (T02)',
    },
    T08: {
      code: 'T08',
      title: 'The Fast-Track Executive Nominee (C-Suite Candidate)',
      subtitle: 'Strategic enterprise vision and high-stakes leadership presence',
      description: 'You think in macro organizational units and speak the language of boards and investors. You command cross-functional alignment and thrive under high responsibility. Prime candidate for senior leadership.',
      tags: ['#ExecutivePresence', '#CSuiteTrack', '#StrategicVision', '#Leader'],
      bestMatch: 'The Relentless Execution Engine (T02)',
      worstMatch: 'The Digital Detox Nomad (T10)',
    },
    T09: {
      code: 'T09',
      title: 'The Inevitable SaaS Founder (Zero-to-One Builder)',
      subtitle: 'Using the corporate environment as a paid accelerator',
      description: 'Corporate red tape stifles your builder instincts. You treat current enterprise workflows as free customer research for your future startup. It is only a matter of time before you launch your own venture.',
      tags: ['#FounderMindset', '#ZeroToOne', '#Bootstrapper', '#FutureSaaSCEO'],
      bestMatch: 'The Sovereign Portfolio Builder (T07)',
      worstMatch: 'The Master of Quiet Quitting (T05)',
    },
    T10: {
      code: 'T10',
      title: 'The Digital Detox Nomad (Nature Seeker)',
      subtitle: 'Yearning for asynchronous freedom and serene landscapes',
      description: 'Urban noise and endless video calls have depleted your nervous system. What you need is not another performance metric, but extended time in nature and asynchronous deep work. Prioritize full remote setups.',
      tags: ['#DigitalNomad', '#NatureSeeker', '#AsyncFirst', '#DeepRecharge'],
      bestMatch: 'The Master of Quiet Quitting (T05)',
      worstMatch: 'The Fast-Track Executive Nominee (T08)',
    },
  },
  seoArticle: 'A deep psychological breakdown of 10 modern workplace archetypes, burnout markers, and career negotiation strategies designed for global professionals.',
};
