import { ToolItem } from '@/types/tool';

export const TOOLS_REGISTRY: ToolItem[] = [
  {
    id: 'work-power',
    slug: 'work-power',
    category: 'test',
    badge: 'HOT',
    title: {
      ko: '직장인 전투력 측정기',
      en: 'Workplace Power Score',
      ja: '社会人力チェッカー',
    },
    description: {
      ko: '회의실 생존력과 오피스 전투 성향을 12개 실전 문항으로 분석합니다.',
      en: 'Analyze your survival skills and battle style in modern office life.',
      ja: 'リアルなオフィス環境での生存力と戦闘スタイルを判定します。',
    },
    icon: 'Briefcase',
    accentColor: 'from-amber-500/20 via-orange-500/10 to-transparent',
    stats: { participants: '12.4K+', rating: '4.9' },
    features: ['12개 문항', '전투력 티어 산출', '오피스 상성 분석'],
  },
  {
    id: 'love-attachment',
    slug: 'love-attachment',
    category: 'test',
    badge: 'HOT',
    title: {
      ko: '연애 애착유형 진단',
      en: 'Attachment Style Test',
      ja: '恋愛愛着タイプ診断',
    },
    description: {
      ko: '갈등 대처 방식과 연락 빈도를 통해 4대 연애 애착 유형을 판별합니다.',
      en: 'Discover your relationship patterns across 4 psychological attachment styles.',
      ja: '4つの愛着スタイルからあなたの恋愛パターンと課題を浮き彫りにします。',
    },
    icon: 'HeartHandshake',
    accentColor: 'from-rose-500/20 via-pink-500/10 to-transparent',
    stats: { participants: '18.9K+', rating: '4.95' },
    features: ['관계 패턴 진단', '갈등 솔루션', '궁합 매칭 가이드'],
  },
  {
    id: 'spending-dna',
    slug: 'spending-dna',
    category: 'test',
    badge: 'NEW',
    title: {
      ko: '소비 DNA & 텅장 분석기',
      en: 'Spending DNA Analyzer',
      ja: '支出DNA診断',
    },
    description: {
      ko: '지출 습관, 충동구매 패턴, 밸런스 게임을 통해 금융 페르소나를 도출합니다.',
      en: 'Identify your financial persona, impulse triggers, and money mindset.',
      ja: 'お金の使い方と衝動買いトリガーからあなたの金銭感覚を分析します。',
    },
    icon: 'Sparkles',
    accentColor: 'from-emerald-500/20 via-teal-500/10 to-transparent',
    stats: { participants: '8.1K+', rating: '4.85' },
    features: ['금융 페르소나', '지출 누수 지점 포착', '절약 처방전'],
  },
  {
    id: 'social-battery',
    slug: 'social-battery',
    category: 'test',
    badge: 'NEW',
    title: {
      ko: '사회적 배터리 용량 테스트',
      en: 'Social Battery Meter',
      ja: 'ソーシャルバッテリー診断',
    },
    description: {
      ko: '내향/외향 스펙트럼과 모임 후 에너지 방전 속도, 최적 충전법을 진단합니다.',
      en: 'Measure your energy drain rates and discover your ideal recharge routine.',
      ja: '人間関係で消耗するエネルギーの回復速度と最適な充電法を診断。',
    },
    icon: 'Zap',
    accentColor: 'from-blue-500/20 via-cyan-500/10 to-transparent',
    stats: { participants: '9.7K+', rating: '4.9' },
    features: ['배터리 잔량 산출', '방전 트리거 파악', '1인 힐링 처방'],
  },
  {
    id: 'ai-prompt-analyzer',
    slug: 'ai-prompt-analyzer',
    category: 'ai',
    badge: 'AI',
    title: {
      ko: 'AI 페르소나 추출기 (준비중)',
      en: 'AI Persona Extractor',
      ja: 'AIペルソナ抽出機',
    },
    description: {
      ko: '자연어 대화 데이터를 분석해 사용자의 의사결정 방식과 숨겨진 성향을 모델링합니다.',
      en: 'Deep learning behavioral modeling based on conversation traces.',
      ja: '対話データから意思決定パターンと潜在的傾向をAIが分析します。',
    },
    icon: 'Cpu',
    accentColor: 'from-purple-500/20 via-indigo-500/10 to-transparent',
    stats: { latency: 'Fast' },
    features: ['오픈소스 LLM 파이프라인', '실시간 감정 분석', '벡터 성향 맵'],
  },
];
